version: '3.3'

services:
  # Servicio para la aplicación NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "8089:8089"
    depends_on:
      - mongo-db
    volumes:
      - .:/app  # Solo en desarrollo: mapea los archivos locales al contenedor
    command: yarn start:dev  # Modo desarrollo: hot reload
    networks:
      - app-network

  # Servicio para MongoDB
  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: